grep NDF fitoutput/textSTART0STOP10.txt | sed 's/_/:/g'  > /tmp/text.txt
grep NDF fitoutput/textSTART10STOP20.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART20STOP30.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART30STOP40.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART40STOP50.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART50STOP60.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART60STOP70.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART70STOP80.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART80STOP90.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART90STOP100.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART100STOP110.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART110STOP120.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART120STOP130.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART130STOP140.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART140STOP150.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART150STOP160.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART160STOP170.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART170STOP180.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART180STOP190.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART190STOP200.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART200STOP210.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART210STOP220.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART220STOP230.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART230STOP240.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART240STOP250.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART250STOP260.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART260STOP270.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART270STOP280.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART280STOP290.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART290STOP300.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART300STOP310.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART310STOP320.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART320STOP330.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART330STOP340.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART340STOP350.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART350STOP360.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART360STOP370.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART370STOP380.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART380STOP390.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART390STOP400.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART400STOP410.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART410STOP420.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART420STOP430.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART430STOP440.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART440STOP450.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART450STOP460.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART460STOP470.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART470STOP480.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART480STOP490.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART490STOP500.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART500STOP510.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART510STOP520.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART520STOP530.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART530STOP540.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART540STOP550.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART550STOP560.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART560STOP570.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART570STOP580.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART580STOP590.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART590STOP600.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART600STOP610.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART610STOP620.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART620STOP630.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART630STOP640.txt | sed 's/_/:/g'  >> /tmp/text.txt
grep NDF fitoutput/textSTART640STOP650.txt | sed 's/_/:/g'  >> /tmp/text.txt
